services:
  - type: web
    name: jesusinho-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: OPENAI_API_KEY
        value: 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
      - key: HF_API_KEY
        value: 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
      - key: AI21_API_KEY
        value: 876280bd-b6bb-48c1-9821-e1f847daa3c6
