services:
  - type: web
    name: jesusinho-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: OPENAI_API_KEY
        value: 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
      - key: HF_API_KEY
        value: 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
      - key: AI21_API_KEY
        value: 876280bd-b6bb-48c1-9821-e1f847daa3c6
