services:
  - type: web
    name: jesusinho-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: OPENAI_API_KEY
        value: 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
      - key: HF_API_KEY
        value: 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
      - key: AI21_API_KEY
        value: 876280bd-b6bb-48c1-9821-e1f847daa3c6
